on:
  push:
    branches-ignore:
      - "gh-pages"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build
      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-artifacts
          path: dist
          retention-days: 5
      - name: Download Uploaded Built Artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-artifacts
      - name: Print the final result
        shell: bash
        run: |
          ls /dist
env:
  YARN_GPG: no
